### ISSUE TITLE
What's Kowtow?

### ISSUE THREAD

**Issue by neilpanchal** [caffeine-overload/bandinchina#10]
I had to look it up, I've never heard of it. Suggestion is to use a common english term such as `bow-down`.

**Comment by mroach** [comment]
It's not an obscure word, and it's a perfectly accurate term to describe what's going on. And as bonus fun, it's a loan word from Cantonese which is the primary language of Hong Kong.

**Comment by neilpanchal** [comment]
@mroach Fair enough, closing the issue.
