### ISSUE TITLE
Riot games

### ISSUE THREAD

**Issue by Shabbypenguin** [caffeine-overload/bandinchina#101]
Wholly owned by Tencent, and have issued statements saying they don't want people discussing HK or anything of the like.

https://www.reddit.com/r/pcgaming/comments/di3u7i/riot_games_asks_casters_and_players_not_to/

https://dotesports.com/league-of-legends/news/riot-games-appears-to-censor-hong-kong-during-worlds-2019-broadcasts

**Comment by caffeine-overload** [comment]
added

**Comment by SashaRyder** [comment]
To be fair, Riot are saying that politics should be kept off air, which seems understandable considering casters and players should be talking about the game rather than what's going on atm with HK and China.

**Comment by Shabbypenguin** [comment]
@SashaRyder just happens to be convenient timing for a company wholly owned by the chinese?

**Comment by SashaRyder** [comment]
I understand they're owned by tencent, but there's a huge different between being bad because they're Chinese and being bad because they're forcing censorship. If they're not really doing the latter but asking for politics to be kept off air, I think that's fair.

**Comment by RA-Kooi** [comment]
They also censor certain words from statuses: https://twitter.com/daokedao1234/status/1186067815209549824
