### ISSUE TITLE
Probably counts, Tarantino says he wont recut Once Upon a Time in Hollywood to bow to chinese temper tantrums.

### ISSUE THREAD

**Issue by LenKagetsu** [caffeine-overload/bandinchina#103]
https://variety.com/2019/film/news/quentin-tarantino-once-upon-a-time-in-hollywood-china-1203375792/

The only real complaint on record is Bruce Lee's daughter taking issue with how Quentin portrays him, but even in life the opinions around the man were very divisive.

**Comment by caffeine-overload** [comment]
Added him
