### ISSUE TITLE
Could u please add DJ zedd and pewdiepie to the whitelist?

### ISSUE THREAD

**Issue by ShoForGitHub** [caffeine-overload/bandinchina#104]

**Comment by LenKagetsu** [comment]
They're individuals, not companies.

**Comment by caffeine-overload** [comment]
I think maybe pewdiepie counts? I bet he could have made a lot of money from China if he wanted to

**Comment by caffeine-overload** [comment]
Looks like pewdiepie wasn't banned in China for his comments
