### ISSUE TITLE
It's astonishing that supporting the statements about breaking up other nations is a fashion in US

### ISSUE THREAD

**Issue by DiamondI** [caffeine-overload/bandinchina#11]
It's **astonishing** that **supporting** the statements about **breaking up other nations** is a fashion in US !

**Comment by mroach** [comment]
Taiwan is already a separate country; there's nothing to break-up.

Suggest closing this as a non-issue/wontfix.

**Comment by DiamondI** [comment]
Oh, it's true that you're a group of people who are delighted to support the allegation about breaking up other nations. Maybe I can stand with 911? And say that the attack was for supporting so-called "freedom of speech"? It's totally ridiculous!

**Comment by kalleboo** [comment]
> Maybe I can stand with 911? And say that the attack was for supporting so-called "freedom of speech"?

Yes, you are free to say that. You can tell since the U.S. government has not banned GitHub or deleted your comment as the Chinese government would have.

**Comment by DiamondI** [comment]
> Maybe I can stand with 911? And say that the attack was for supporting so-called "freedom of speech"?
> 
> Yes, you are free to say that. You can tell since the U.S. government has not banned GitHub or deleted your comment as the Chinese government would have.

Then, the companies such as blizzard are also free to do things like punish the player who didn't follow the rule of blizzard since U.S. government has not banned blizzard not doing so. Then, what's the real reason that those companies are listed in the blacklist? Is it exactly about the freedom of speech? I'm afraid I can't agree with such allegation.

**Comment by kalleboo** [comment]
> follow the rule of blizzard since U.S. government has not banned blizzard not doing so

The companies are trying to avoid the Chinese government banning them in China, not the US government.

**Comment by DiamondI** [comment]
> follow the rule of blizzard since U.S. government has not banned blizzard not doing so
> 
> The companies are trying to avoid the Chinese government banning them in China, not the US government.

Is US government banning this for doing so ? If not, then they're free to do such things. Again, what's the real reason that those companies are listed in the blacklist ?

**Comment by mroach** [comment]
Yes, companies are mostly free to behave as they wish (there are limits; they can't steal intellectual property from others, accept bribes, and other shameful behaviour). If companies want to punish players to appease China, that's their right. But then it's also the right of consumers to protest and boycott the company because of their behaviour.

**Comment by DiamondI** [comment]
> Yes, companies are mostly free to behave as they wish (there are limits; they can't steal intellectual property from others, accept bribes, and other shameful behaviour). If companies want to punish players to appease China, that's their right. But then it's also the right of consumers to protest and boycott the company because of their behaviour.

Then, this is nothing to do with so-called "freedom of speech". You are just doing things that may ruin the symbiosis between our countries.

**Comment by lazycrypt** [comment]
One should not be symbiotic with an government running concetration camps and is using prisoners as organ farms.

**Comment by Hoggord** [comment]
I'm new to Github so please let me know if anything I say is against the rules and I will gladly edit/omit.

Firstly, thank you to the creator for compiling this collection of information. It is critical to our democracies that we stomp out corporations that so blindly & ignorantly support an oppressive regime such as China's ruling class. People like you are keeping the flame burning and are invaluable to the future.

Secondly, there is a massive and highly organized campaign at the root of the censorship of Western media that is presently getting so much attention. It is sometimes referred to as the United Front(統一戰線 for our Chinese readers), and can be summarized as China's global propaganda arm. There are many resources that can further explain China's policies/practices related to methods of influencing media and geopolitics.

Here is a PDF summarizing the work of an Academic Outreach Workshop program of the Canadian Security Intelligence Service(CSIS):

https://www.canada.ca/content/dam/csis-scrs/documents/publications/CSIS-Academic-Outreach-China-report-May-2018-en.pdf

**Comment by joshua-turner** [comment]
> Maybe I can stand with 911? And say that the attack was for supporting so-called "freedom of speech"? It's totally ridiculous!

> Then, the companies such as blizzard are also free to do things like punish the player who didn't follow the rule of blizzard since U.S. government has not banned blizzard not doing so.

It's remarkable how close you are to understanding. You, as a private citizen (or company), are free to say/express yourself however you wish. That includes bowing to Chinese censorship.

Likewise, consumers are able to create lists like this to boycott you for such actions. We don't have to be considerate of "symbiosis between our countries", because we're allowed to not care about that. In fact, we're allowed to actively work _against_ symbiosis with a dictatorship.

**Comment by caffeine-overload** [comment]
@Hoggord I did actually create another repo, https://github.com/caffeine-overload/anti_prop, for tracking chinese propaganda on Reddit. It is obviously not academic research, but simply based on my observations. This repo has got much more attention so I put my focus into this one, and it seems like most people on reddit have "woken up" to disinformation attempts anyway

Thanks for the link to the research paper

**Comment by WAUthethird** [comment]
Probably good to close as a non-issue.

**Comment by jun1st** [comment]
Twitter and Facebook did

> Yes, you are free to say that. You can tell since the U.S. government has not banned GitHub for not deleting your comment as the Chinese government would have.
>

**Comment by WAUthethird** [comment]
> Twitter and Facebook did
> 
> > Yes, you are free to say that. You can tell since the U.S. government has not banned GitHub for not deleting your comment as the Chinese government would have.

Doesn't matter, as they are free to do that if they so choose. Likewise, I (and everyone else here, including you) are free to criticize these companies for the choices they make. The Chinese government has the power to delete comments posted on their websites, because of the way their laws are set up. Due to free speech, of course, if the US government were to delete comments, it would be unconstitutional.

**Comment by jun1st** [comment]
> > Twitter and Facebook did
> > > Yes, you are free to say that. You can tell since the U.S. government has not banned GitHub for not deleting your comment as the Chinese government would have.
> 
> Doesn't matter, as they are free to do that if they so choose. Likewise, I (and everyone else here, including you) are free to criticize these companies for the choices they make. The Chinese government has the power to delete comments posted on their websites, because of the way their laws are set up. Due to free speech, of course, if the US government were to delete comments, it would be unconstitutional.

Donald Sterling may wants to exercise his rights of free speech

**Comment by starer93** [comment]
> > Twitter and Facebook did
> > > Yes, you are free to say that. You can tell since the U.S. government has not banned GitHub for not deleting your comment as the Chinese government would have.
> 
> Doesn't matter, as they are free to do that if they so choose. Likewise, I (and everyone else here, including you) are free to criticize these companies for the choices they make. The Chinese government has the power to delete comments posted on their websites, because of the way their laws are set up. Due to free speech, of course, if the US government were to delete comments, it would be unconstitutional.

so which Chinese law are you referring to?

**Comment by WAUthethird** [comment]
> > > Twitter and Facebook did
> > > > Yes, you are free to say that. You can tell since the U.S. government has not banned GitHub for not deleting your comment as the Chinese government would have.
> > 
> > 
> > Doesn't matter, as they are free to do that if they so choose. Likewise, I (and everyone else here, including you) are free to criticize these companies for the choices they make. The Chinese government has the power to delete comments posted on their websites, because of the way their laws are set up. Due to free speech, of course, if the US government were to delete comments, it would be unconstitutional.
> 
> so which Chinese law are you referring to?

Apologies, ‘law’ was incorrect in this case, however the government holds so much power over its own social media services that it can request comments be deleted and users be banned, due to their parent company’s status within the state.

**Comment by cbluth** [comment]
Free Hong Kong, free Tibet!

**Comment by ThunderLT** [comment]
@mroach The 9/11 incident is the retribution that Americans deserve. They slaughtered Arabs and Islamists and caused revenge from extremists. This is my freedom of speech. The CIA and the US aircraft carrier can kill me even in Shanghai, just like the Snowden incident. The Americans are calling for privacy protection while eavesdropping on the world’s bed

**Comment by ThunderLT** [comment]
@WAUthethird  So why are many of the comments on Facebook that support Hong Kong's belonging to China be removed, and the US government is unconstitutional?

**Comment by mroach** [comment]
@ThunderLT Yep, that's your freedom of speech indeed. I wouldn't call it very inspired speech by any means. buy you're welcome to say it without fear of US government retribution. People on the other hand will likely think you're an uneducated simpleton and laugh at you.

**Comment by ThunderLT** [comment]
@mroach  So, the brainwashing education you receive must be very advanced. Which pheasant university did you graduate from, Harvard, Stanford, Berkeley?

**Comment by caffeine-overload** [comment]
I'm closing this now

**Comment by cirosantilli** [comment]
See also: https://github.com/cirosantilli/china-dictatorship/tree/ccbfc943e482a995b59e4e4cb52dfa9f2a24ff67#separatism
