### ISSUE TITLE
Remove Chinese App Store Censorship from Apple's entry

### ISSUE THREAD

**Issue by hyperparsa** [caffeine-overload/bandinchina#12]
While Apple removing the Taiwan flag in Hong Kong is perfectly suitable, Apple removing VPN apps and censoring music in the Chinese version of the App Store and Apple Music, does not fit in the theme of "exported censorship" that China demands from foreign companies in foreign territories, and shouldn't be in the list in my opinion.

**Comment by caffeine-overload** [comment]
I think you have a good point here

**Comment by caffeine-overload** [comment]
Didn't they actually just remove the police tracking app in Hong Kong after approving it? Maybe I should qualify the statement in the table

**Comment by caffeine-overload** [comment]
I've changed it to be specifically about the police app, removing the general statement about VPN apps
