### ISSUE TITLE
Protesters are fascinating for fascism, Kristallnacht In HongKong,But they ignoring the fact

### ISSUE THREAD

**Issue by iamurdaddymyson** [caffeine-overload/bandinchina#122]
1. Discrimination against people who speak Mandarin and write simplified characters, and conduct verbal and physical violence against them, infringing on their personal safety and financial security
2.  Violence against dissidents on the streets, arson, breaking shops, infringing on the principle of free trade
3.  Exposing information about dissidents and police and their families, harassing and intimidating them, and exercising school violence on their children
4.  breaking, arson and robbery against dissident shops
5.  Forcing dissidents to accept their political views by means of intimidation, insults, and snoring

**Comment by LenKagetsu** [comment]
Comparing that to Kristallnact? You're so ignorant of history I bet you don't know what happened on the 4th of June 1989 in your own country's landmark of Tiananmen Square.

**Comment by MoistCode** [comment]
We should close this because this is a list of non-sourced ranting and does not change the content of the site in any way. Don’t bother entertaining this.

**Comment by caffeine-overload** [comment]
> Forcing dissidents to accept their political views by . . . snoring

Have you tried sleeping in a different room?
