### ISSUE TITLE
hkprotester-nazi

### ISSUE THREAD

**Issue by iamurdaddymyson** [caffeine-overload/bandinchina#125]
You are the one who have no kownledge of the history
1. did you be informed of your loved the UK state never giving you the voting right? it is the chinese government that gives it.
2. i know what happened ,and i also know something you didnt konw that is not conducive to you brainwashed into anti-Chinese elements, such as they burning a person in live
3. Be careful, the Kurdish end is your future.

**Comment by iamurdaddymyson** [comment]
wake up from the VR hero cosplay that cost hk future

**Comment by caffeine-overload** [comment]
>  did you be informed of your loved the UK state never giving you the voting right?

I think you are a bit confused. The UK gives BNO passport holder the right to vote in UK general elections but not the right to live in the UK (I agree it's bizarre). It was also the UK which set up the mini-democracy when they left. It is China who is trying to interfere in the affairs of the mini-democracy

 >  i know what happened ,and i also know something you didnt konw that is not conducive to you brainwashed into anti-Chinese elements

I don't even understand this sentence. 

 >  they burning a person in live

Who is "they"? HK protestors? I will need some evidence (CGTN doesn't count). Are you also aware that the HK police used agent provocateurs? 

>  Be careful, the Kurdish end is your future.

Implying that the PLA will invade HK? The CCP are not that stupid. Any PLA actions will result in China being cut off from the world economy.
