### ISSUE TITLE
This repo listing dissidents‘ name is disgusting, The yellow umbrella can't cover the black atrocities

### ISSUE THREAD

**Issue by iamurdaddymyson** [caffeine-overload/bandinchina#127]
1. Don't draw a target first, then attack what Beijing hasn't done. Your analogy is wrong. Anti-secession is the consensus of all. Why don't you just ask the Spanish government and Boris if  willing to let Catalunya and Scotland become independent? Go ask the White House if willing  to let California be independent? The company you listed listens to the will of the people. Even if you list so many names and expose the information of so many dissidents,attacking and intimidating them, boycotting them, you can't let 1.4 billion people stop speaking against you.
2. This repo listing dissidents is disgusting, don't close my voice. i will paste my voice that were banned by you.
3. The yellow umbrella can't cover the black atrocities, and the truth will eventually appear in front of the world, even if you delete more posts on Facebook and Twitter.Under the lofty slogan, hide your black evil, don't be ISIS
4 .what behind the great , correct,and justice slogan“for freedom“ ，is the innocent children who are bullied, the law enforcers who are slandered, the violence that be beautified, the traffic that be destoryed, the shops that be looted, the Dissidents who were besieged and beaten, just like the Cultural Revolution "for the people"，as well as Hitler ”For Germany“

**Comment by The1Freeman** [comment]
What is your goal?

**Comment by iamurdaddymyson** [comment]
> 你的目标是什么？

just voice the truth ，do not be afraid~

**Comment by The1Freeman** [comment]
The truth that the Chinese government is pulling off some shady things in the western side of this planet?
Yeah, it's relatively old news, but it's still something that needs to be talked about.

**Comment by iamurdaddymyson** [comment]
> The truth that the Chinese government is pulling off some shady things in the western side of this planet?
> Yeah, it's relatively old news, but it's still something that needs to be talked about.

Do you know how Hitler smeared the Jews? using anti-Semitism propaganda materials to prove that the Jewish is evil and they did lots of badness，which has once again become popular in today's magical world, of course the role of jewish has become  chinese. After all, many people's mind-color are Nazis.
In that era, everyone believed that anti-Semitic is politically correct, just as anti-China is now politically correct. 
Anti-Semiticism is a propaganda that European nation states--which failed to overcome the counterfeiting of the cyclical crisis of capitalism--manufactured. Chinese exclusion is a contradiction created by Western colonists in order to maintain the rule of the third world. The Yellow Peril is a political mobilization of white religious regimes facing the rise of Asia.
The spiritual core of the three things is the same.

**Comment by iamurdaddymyson** [comment]
When Japanese fascists invaded China, they used the method of "governing China with China" to let the Chinese rush to the front line of anti-China. Now the West have copied this means, brainwashing Hong Kong young people and Taiwanese to rush to the front line of anti-China.

**Comment by The1Freeman** [comment]
How dare you even bring Nazi Germany into this? What's happening in todays world is nothing compared to the 6 million jews who were sent to concentration camps to be gassed, dying because of it.
I don't need to tell you how wrong that is, but seeing as how disconnected you are from reality, that is something you most likely support as well.

You do realize that the citizens of Hong Kong are protesting, it is the Chinese Govt. telling you otherwise and you fully buy into it, what a shame really.

**Comment by iamurdaddymyson** [comment]
> 您甚至敢把纳粹德国带到这里吗？与被送到集中营被毒死，死于死亡的600万犹太人相比，当今世界上发生了什么。
> 我不需要告诉你那是怎么错，但是看到你与现实之间有多疏离，那也是你最有可能支持的事情。
> 
> 您确实意识到香港市民在抗议，这是中国政府。告诉你，否则你全买了，真可惜。

"How dare you", what a ridiculous word. the people dare, the truth is dare, the truth stings you? Smashing Chinese-funded shops, intimidating and robbing people who speak Mandarin,  the law enforcers‘  children are bullied at school. I have been amazed at times that cruelty can go unpunished, propaganda machines and even beautify this shameful violence, and you are also involved in blacklist repo, oppressing  businesses that runs counter to your political views. Everything what happened is like a replica of Kristallnacht. Black cloth covers your eyes, yellow lies are designing your thoughts. wake up, god bless you.

**Comment by iamurdaddymyson** [comment]
> You do realize that the citizens of Hong Kong are protesting, it is the Chinese Govt. telling you otherwise and you fully buy into it, what a shame really.

I will return your words to you.You don't even  realize that the  Kristallnacht happended in  Hong Kong , it is the  propaganda machines, telling you otherwise and rumors and you fully buy into it, what a shame really.

**Comment by caffeine-overload** [comment]
More unsourced assertions about protestor behaviour and propaganda regurgitating. 

If anyone is behaving like the NSDAP (Nazi party), it is the CCP with their ethno-nationalism, scapegoating of foreigners and minorities for social and economic issues, and of course their mass incarceration of Uighurs. You have an extremely warped view of history and are completely deluded.

**Comment by iamurdaddymyson** [comment]
> 关于示威者行为和反叛宣传的更多无依据的断言。
> 
> 如果有人像纳粹党（NSDAP）那样行事，那就是中共与他们的民族民族主义，为社会和经济问题而成为外国人和少数民族的替罪羊，当然还有他们对维吾尔人的大规模监禁。您对历史有极度扭曲的看法，并且被完全迷住了。

stop colsing my voice that saying the truth you are not willing to let your guys be informed of
