### ISSUE TITLE
I think shaming companies wouldn't work

### ISSUE THREAD

**Issue by 25DegreeCelsius** [caffeine-overload/bandinchina#129]
If it was easy, why we can't dethrone Xi from leadership?

**Comment by 25DegreeCelsius** [comment]
Most of the blacklisted organizations, in technical context, can be substituted. But in sentimental context, they can't.

**Comment by 25DegreeCelsius** [comment]
The problem is, by naming and shaming them, you're causing them to discount their products and services. And the whole boycott is gone.

**Comment by iamurdaddymyson** [comment]
Go, boycott the whole world
