### ISSUE TITLE
what behind the great , correct,and justice slogan“for freedom“ ，is the innocent children who are bullied, the law enforcers who are slandered, the violence that be beautified, the traffic that be destoryed, the shops that be looted, the Dissidents who were besieged and beaten, just like the Cultural Revolution "for the people"，as well as Hitler ”For Germany“

### ISSUE THREAD

**Issue by iamurdaddymyson** [caffeine-overload/bandinchina#136]

**Comment by caffeine-overload** [comment]
https://www.bbc.co.uk/news/world-asia-china-50281914

Tell me who are the terrorists here. It is the CCP supporters. Chinese state media lies about the protests.

**Comment by iamurdaddymyson** [comment]
> https://www.bbc.co.uk/news/world-asia-china-50281914
> 
> Tell me who are the terrorists here. It is the CCP supporters. Chinese state media lies about the protests.

Allow him to be besieged, insulted, humiliated, beaten, intimidated by group of the black men, but he is banned to fight back after being hurt. This is your logic.
