### ISSUE TITLE
It is a riot, not a peaceful protest. Stand with China!

### ISSUE THREAD

**Issue by PiensXV** [caffeine-overload/bandinchina#14]
What is happening in Hong Kong is not a peaceful protest, but a riot, which ruins Hong Kong as well as people's daily lives. 
If you don't know what actually happened, just search for information about how Hong Kong policemen were injured, and [how a journalist who support Hong Kong Police was badly hurt by so-called protesters](https://www.wsj.com/articles/chinese-reporter-assaulted-at-hong-kong-airport-becomes-mainland-hero-11565789917).
[They also attack metro system](https://www.youtube.com/watch?v=ByS_9Ah6uV4) ,causing millions of people cannot commute.
Freedom does not mean you can do anything you want, especially when you harm others' well-being. If you call it freedom, it is fine.

**Comment by gooca** [comment]
Undercover China-backed Hong Kong police dressed like protesters, at a peaceful protest, and tried to incite violence before being outed by the protesters as HK police, then you come on here and try to say the protesters are violent. Hilarious.

**Comment by caffeine-overload** [comment]
For anyone reading who is in China, remember that the Chinese media will misrepresent what happened and conveniently leave out incidents where "innocent bystanders" threatened people with claw hammers and rammed into protestors with their cars with the intent of causing serious injury or death. 

The vast majority of violence has been perpetrated by raptors and pro-beijing gangs. 

As another comment has already said, the HK police are confirmed to have used agent provocateurs to commit false-flag violence.

Closing the issue as it is a: false, and b: does not contribute to the list
