### ISSUE TITLE
Allow those unfamiliar with Git to make requests

### ISSUE THREAD

**Issue by MoistCode** [caffeine-overload/bandinchina#155]
There are many people who are not familiar with Github so I figured we should have a form to request changes to the information on the site.

**Comment by LenKagetsu** [comment]
I've just made issues and posted a link more than once, no complaints so far.

**Comment by MoistCode** [comment]
It's for those "not familiar with GitHub. Just a traditional consumer-user.

**Comment by caffeine-overload** [comment]
It has potential to be abused though, just look at the issues page.

Perhaps a subreddit?

**Comment by LenKagetsu** [comment]
> It has potential to be abused though, just look at the issues page.
> Perhaps a subreddit?

Considering the sheer amount of pro-china subs and the incompetence of the admins, plus reddit's callout culture and love of harassing people, this would be a terrible idea. Besides, posting an issue on here is a trivial matter, it's not like you expect them to fork and such.

**Comment by MoistCode** [comment]
When users need to make a GitHub account and learn how to create an issue, it is not a trivial matter. It is basic UX that the more work they need to do, the less likely they would do it.

I will close the issue for now. We can revisit if I come across another person that mentions they want to contribute.
