### ISSUE TITLE
What you want to know is not the truth

### ISSUE THREAD

**Issue by YuunYang** [caffeine-overload/bandinchina#162]
It is wrong, Politically Wrong for a company to respect China, but everything ANTI-CHINA is current, it's funny, I think you never been to Hong Kong, to experience this city witch are destroying by those rioters, or I think you guys even reluctant to see the related news. 

I see you added Notepad++ to your whitelist, who released a `Free Uyghur(解放维吾尔族)` version, maybe you have never talked to a Uyghur, but you added it, just because it ANTI-CHINA.

Last, hope you guys just focus the tech in Github, you can express your voice in ins or twitter,

**Comment by SephReed** [comment]
I would like to know the truth.  You are from China?

Tell me about your government.

Also, fuck the U.S. government.
