### ISSUE TITLE
Add HSBC, Standard Chartered

### ISSUE THREAD

**Issue by khj0925** [caffeine-overload/bandinchina#165]
https://edition.cnn.com/2020/06/04/business/hsbc-standard-chartered-hong-kong-law-intl-hnk/index.html

HSBC, Standard Chartered publicly support China's national security law for Hong Kong

**Comment by caffeine-overload** [comment]
Noted, will add it. It's not technically censorship but it is a company that is very active in the west publicly voicing support for this extremely concerning law (and by extension the HK authorities and the CCP)

**Comment by khj0925** [comment]
> Noted, will add it. It's not technically censorship but it is a company that is very active in the west publicly voicing support for this extremely concerning law (and by extension the HK authorities and the CCP)

Excuse me, may I ask why you didn't add my suggestion? I waited for THREE MONTHS, but list didn't changed. I saw other company is added, while my suggestion about HSBC, Standard Chartered  didn't added. I'm totally upset.

**Comment by caffeine-overload** [comment]
Chill dawg I was busy and forgot
