### ISSUE TITLE
Article: University of New South Wales deletes tweets construed as pro-HK, claims it's not "in line with our policies"

### ISSUE THREAD

**Issue by LenKagetsu** [caffeine-overload/bandinchina#168]
https://www.abc.net.au/news/2020-08-03/unsw-under-fire-for-deleting-china-social-media-posts/12517306

Of course, facist fragility kicked in and a tantrum was thrown by the usual suspects.

**Comment by caffeine-overload** [comment]
I've added it to the universities list. But maybe I should merge that list with the main one
