### ISSUE TITLE
Add Naver

### ISSUE THREAD

**Issue by piquark6046** [caffeine-overload/bandinchina#175]
You can check it out on https://nid.naver.com/user2/V2Join.nhn?m=agree&lang=en_US.
The homepage of NAVER: https://www.naver.com/
The homepage of NAVER Corp.: https://www.navercorp.com/en/
The GitHub account of NAVER: https://github.com/naver

![Screenshot](https://user-images.githubusercontent.com/37463155/104046380-e82cca00-51d7-11eb-8ef4-6a93a399af2c.png)

**Comment by piquark6046** [comment]
https://www.vlive.tv

![Screenshot](https://user-images.githubusercontent.com/37463155/104297533-e8201900-54ba-11eb-978a-ce902a06511c.png)

**Comment by piquark6046** [comment]
The parent of LINE Corporation is Naver Corp.

https://www.navercorp.com/en
![Screenshot1](https://user-images.githubusercontent.com/37463155/104580972-d6bf4400-5655-11eb-95df-a4319291d632.png)

https://linecorp.com/en/pr/sns
![Screenshot](https://user-images.githubusercontent.com/37463155/104581022-e8085080-5655-11eb-8a26-7bdc3c763d5c.png)

**Comment by DevilNANA** [comment]
Naver is a search portal site in South Korea, and except for Korean, it is often created and neglected. First of all, it seems like a translation error, so it would be better to contact the customer center.

**Comment by piquark6046** [comment]
> 
> 
> Naver is a search portal site in South Korea, and except for Korean, it is often created and neglected. First of all, it seems like a translation error, so it would be better to contact the customer center.

Could you please tell me the email address of Naver?

**Comment by DevilNANA** [comment]
> > Naver is a search portal site in South Korea, and except for Korean, it is often created and neglected. First of all, it seems like a translation error, so it would be better to contact the customer center.
> 
> Could you please tell me the email address of Naver?
> I cannot find the email address of Naver at [this page](https://www.navercorp.com/naver/contact).

In the past, it existed as help@naver.com, but not now. You have to find it on the relevant page in the help center (https://help.naver.com/) and make an inquiry or call by phone. (https://help.naver.com/support/reportCenter/home.help#none)
It is roughly similar to the Google Help  or Facebook Help Center.

**Comment by DevilNANA** [comment]
> > Naver is a search portal site in South Korea, and except for Korean, it is often created and neglected. First of all, it seems like a translation error, so it would be better to contact the customer center.
> 
> Could you please tell me the email address of Naver?
> I cannot find the email address of Naver at [this page](https://www.navercorp.com/naver/contact).

https://kin.naver.com/qna/detail.nhn?d1id=1&dirId=1060106&docId=382085422
I put 1:1 inquiry into NAVER's official account through NAVER Knowledge IN (similar service to Yahoo! Answers or Quora).

**Comment by piquark6046** [comment]
> 
> 
> > > Naver is a search portal site in South Korea, and except for Korean, it is often created and neglected. First of all, it seems like a translation error, so it would be better to contact the customer center.
> > 
> > 
> > Could you please tell me the email address of Naver?
> > I cannot find the email address of Naver at [this page](https://www.navercorp.com/naver/contact).
> 
> https://kin.naver.com/qna/detail.nhn?d1id=1&dirId=1060106&docId=382085422
> I put 1:1 inquiry into NAVER's official account through NAVER Knowledge IN (similar service to Yahoo! Answers or Quora).

Thanks.

**Comment by DevilNANA** [comment]
> > > > Naver is a search portal site in South Korea, and except for Korean, it is often created and neglected. First of all, it seems like a translation error, so it would be better to contact the customer center.
> > > 
> > > 
> > > Could you please tell me the email address of Naver?
> > > I cannot find the email address of Naver at [this page](https://www.navercorp.com/naver/contact).
> > 
> > 
> > https://kin.naver.com/qna/detail.nhn?d1id=1&dirId=1060106&docId=382085422
> > I put 1:1 inquiry into NAVER's official account through NAVER Knowledge IN (similar service to Yahoo! Answers or Quora).
> 
> Thanks.

There have been no answers for about a month. I think it would be nice to just add it to the blacklist.

**Comment by ghost** [comment]
They updated.
![Screenshot](https://user-images.githubusercontent.com/37463155/124587721-7a402300-de47-11eb-9d85-7b45371b4597.png)
