### ISSUE TITLE
Not a company but country.

### ISSUE THREAD

**Issue by MJGrey** [caffeine-overload/bandinchina#20]
I think we should add countries/governments as seperate entities. I've already seen Prague mentioned. Here's news from the Netherlands in regards to Taiwan.

http://focustaiwan.tw/news/aipl/201910090015.aspx

**Comment by caffeine-overload** [comment]
Maybe I can change "companies" to "entities" in the whitelist?

**Comment by PrinceKael** [comment]
I agree with changing it to something like "Entities" to include countries and cities like Prague.

However we might have to handle countries and cities differently if we're talking about their governments, as their stances may be different depending on if it's a single politician, one party or one department that may not represent the whole.

I'm still on board with that though, just something to keep in mind.

**Comment by MJGrey** [comment]
Sounds good. My main aim is to create more structure that reflects the variety/scope of actors at play. I'm cool with whichever direction you take though. Good initiative regardless.
