### ISSUE TITLE
[Feature] add section for individual figures

### ISSUE THREAD

**Issue by Faunsce** [caffeine-overload/bandinchina#23]

**Comment by PrinceKael** [comment]
Should "Individuals" be included as a link to a separate page? Only because there may be a lot of individuals to record and we need some 'barrier of entry' on who to include.

**Comment by Faunsce** [comment]
It may be good to have multiple readmes, one for each massive category.

**Comment by caffeine-overload** [comment]
Yeah, I think separate files for people/celebrities if people want such a list
