### ISSUE TITLE
Add archive links for all sources!

### ISSUE THREAD

**Issue by S-B99** [caffeine-overload/bandinchina#29]
Archive.org is preferred but at least one other source next to it should be added

**Comment by PrinceKael** [comment]
Good idea, I'll start archiving some when I finish my coffee and open a PR.

**Comment by LenKagetsu** [comment]
Do mind that Cloudflare's 1.1.1.1 DNS gets blocked by Archive.is, I'd make a note of that as well.

**Comment by S-B99** [comment]
That's why I said multiple 👍

**Comment by S-B99** [comment]
No word on this?

It's been 2 weeks. Pull request guide lines should reinforce this at the very least, even if it's hard to find time to update all links with archive.org currently

**Comment by caffeine-overload** [comment]
Closing for now, as the priority is low. Although I think any non-news pages (like company websites) should be posted as archive by default, in case the company change their website
