### ISSUE TITLE
Double Standard？你们是双标狗吗？

### ISSUE THREAD

**Issue by 784033619** [caffeine-overload/bandinchina#38]
Is there a bottom line when you say "freedom of speech"Is what you call "freedom of speech" really allowed to say anything? Do you dare to post negative comments about black people on Twitter and FaceBook? Or dare you publicly support negative comments about your black friends?
No, you dare not. If you dare to say or support these comments, you will surely be punished by the league like clippers owner Donald Sterling, when Adam Silver announced that he was banned for life and fined $2.5 million by the league. What about you? What punishment will you receive???
We, like you, will not agree with or even make racist remarks, because premier zhou enlai once said, "seek common ground while reserving differences."
"Racial discrimination" is the bottom line of your "freedom of speech", and "national sovereignty" is the bottom line of our "freedom of speech".
Your support for "freedom of speech" in Hong Kong is to support their efforts to split the country. In our eyes, this is as serious as "racial discrimination".
If you don't know our Chinese situation, please comment after you know it or shut up!
If you do not support the "freedom of speech" of "racial discrimination", please do not support the "freedom of speech" of Hong Kong abandoned waste younth.
    你们所说的“言论自由”是否是有底线的？难道你们所谓的“言论自由”真的是可以什么都说的吗？你们敢不敢在Twitter、FaceBook上面发表对黑人的负面评论呢？又或者你们是否敢公开支持对于黑人朋友负面的评论呢？
    不，你们不敢，如果你们敢说或者支持这些评论，你们肯定会像快船老板斯特林（Donald Sterling）一样，他被联盟处罚，肖华（Adam Silver）宣布他被联盟终生禁赛、罚款250万美元，那么你们呢？你们会受到什么处罚？？？
     我们和你们一样不会赞同甚至发表“种族歧视”相关言论，因为周恩来周总理曾经说过：“求同存异”。
    “种族歧视”是你们“言论自由”的底线，“国家主权”就是我们“言论自由”的底线。
     你们支持香港“言论自由”，就是支持他们搞“国家分裂”，在我们眼里，这个性质和“种族歧视”一样严重！
     如果你们不了解我们中国国情请了解之后再来评论要么就闭嘴！
     如果你们不支持“种族歧视”的“言论自由”那么也请不要支持香港废青们的“言论自由”。

**Comment by MasterMann** [comment]
Fuck you, CCP shill. Go suck on your president's cock

**Comment by 784033619** [comment]
> Fuck you, CCP shill. Go suck on your president's cock

U pieces of shit. Have u ever read it ,sucker

**Comment by Roiocam** [comment]
@MasterMann  Stupid, There is one thing u should know that most of chinese don't have a change to  choose our leader. I believe everyone will love there homeland, no matter what it is, it could be a county, and could be a region. u can blame our gov, if they hurt your interests. But ,don't let this rise to the nation and the people

**Comment by fixmycode** [comment]
Your comment doesn't make a disservice to the fact that governments should tend to their people needs, as you're part of a democracy. 

Now, part of your country feels like their government is not representing or taking care of their needs. You have a choice: you either listen and understand those needs, and take action so your government service them, or you simply accept the fact that your government is not needed anymore, and move on. 

Borders, sovereignty, are imaginary lines, put there for ease of management, and if you can't manage them, and you keep fighting for it, you are not "protecting your sovereignty", that is just **greed**.

I know that you care about your country.

Countries are made by the people, for the people, and people in the Hong Kong area don't feel like part of your country any more. That's how I feel about this whole thing.

**Comment by ZioA5260** [comment]
> Your comment doesn't make a disservice to the fact that governments should tend to their people needs, as you're part of a democracy.
> 
> Now, part of your country feels like their government is not representing or taking care of their needs. You have a choice: you either listen and understand those needs, and take action so your government service them, or you simply accept the fact that your government is not needed anymore, and move on.
> 
> Borders, sovereignty, are imaginary lines, put there for ease of management, and if you can't manage them, and you keep fighting for it, you are not "protecting your sovereignty", that is just **greed**.
> 
> I know that you care about your country.
> 
> Countries are made by the people, for the people, and people in the Hong Kong area don't feel like part of your country any more. That's how I feel about this whole thing.
Can you represent Hong Kong? Maybe you think that abandoned waste younth can represent Hong Kong?

**Comment by recolic** [comment]
香港要的是直接选举。您又代表香港想独立啦？

**Comment by 784033619** [comment]
> Your comment doesn't make a disservice to the fact that governments should tend to their people needs, as you're part of a democracy.
> 
> Now, part of your country feels like their government is not representing or taking care of their needs. You have a choice: you either listen and understand those needs, and take action so your government service them, or you simply accept the fact that your government is not needed anymore, and move on.
> 
> Borders, sovereignty, are imaginary lines, put there for ease of management, and if you can't manage them, and you keep fighting for it, you are not "protecting your sovereignty", that is just **greed**.
> 
> I know that you care about your country.
> 
> Countries are made by the people, for the people, and people in the Hong Kong area don't feel like part of your country any more. That's how I feel about this whole thing.

But they are still Chinese after all, they have not changed their nationality, if he thinks the country is bad, they can march and demonstrate, they can oppose some actions of the government. But do you know what they did? They disrupt public transport in cities, destroy urban construction, destroy shops that do not support them, beat innocent citizens and throw Molotov cocktails at police. I think they look like terrorists.
但他们毕竟还是中国人，还没有改国籍，如果他觉得国家不好，他们可以游行示威，可以反对政府一些做法。但是你知道他们做了些什么吗？他们破坏城市公共交通，毁坏城市建设，不支持他们的商店就破坏，殴打无辜市民，向警察扔燃烧瓶。我觉得他们这像恐怖分子。

**Comment by fixmycode** [comment]
> Can you represent Hong Kong? Maybe you think that abandoned waste younth can represent Hong Kong?

@ZioA5260 First, I think calling anyone "abandoned waste" is derogatory.
Secondly, I think they're representing themselves just fine. It's not my land, it's theirs.

> if he thinks the country is bad, they can march and demonstrate, they can oppose some actions of the government.

@784033619 That's interesting. 

> They disrupt public transport in cities, destroy urban construction, destroy shops that do not support them, beat innocent citizens and throw Molotov cocktails at police. I think they look like terrorists.

Would you support their demonstration if they didn't incur in violent behavior? Going back to the topic of this issue: The information provided by this list is the **least** violent behavior possible and I'm sure it's an example of solidarity. So if you think you can show solidarity with people that want to show their nonconformity with their government, you could support these (foreign) demonstrators.

**Comment by rocketNeck** [comment]
>"Racial discrimination" is the bottom line of your "freedom of speech"

No it is not.
People can post negative things about black people on twitter and Facebook. And they do. All the time. (I was just in an argument with a proud racist on twitter yesterday) With freedom of speech there is NO bottom line. A company has the right to ban a user for breaking the TOS. But the government has no right to shut down or remove any speech. In the US you can start a pro ISIS website if you want. You can have a racist website, and the government can not censor that. That's how it works. But a company (NBA) I sign a contract with may fine me for breaking with policy, because it is in our contract. The government may NOT do anything to me based on my speech. The government may NOT remove a website for racist content, religious content, anti-gay content. This list is a part of that free speech. Companies who want to have Pro-China leanings and censor people are free to do that but we have the right to not buy their products. We have to right to know who they are and keep this repo. And we can say anything we want in the US because we are free to do so.

**Comment by 784033619** [comment]
> > Can you represent Hong Kong? Maybe you think that abandoned waste younth can represent Hong Kong?
> 
> @ZioA5260 First, I think calling anyone "abandoned waste" is derogatory.
> Secondly, I think they're representing themselves just fine. It's not my land, it's theirs.
> 
> > if he thinks the country is bad, they can march and demonstrate, they can oppose some actions of the government.
> 
> @784033619 That's interesting.
> 
> > They disrupt public transport in cities, destroy urban construction, destroy shops that do not support them, beat innocent citizens and throw Molotov cocktails at police. I think they look like terrorists.
> 
> Would you support their demonstration if they didn't incur in violent behavior? Going back to the topic of this issue: The information provided by this list is the **least** violent behavior possible and I'm sure it's an example of solidarity. So if you think you can show solidarity with people that want to show their nonconformity with their government, you could support these (foreign) demonstrators.

As long as it's legal, I support it. The problem is that they are illegal now, I don't support them, so will you support them?
只要是合法游行，我就支持；问题是现在他们不合法了，我不支持，那你会去支持吗？

**Comment by hachikujimayoi298** [comment]
Discriminative speech in US may cost you a job or two, but any political speech that's not rubber-stamped by the authority may get you arrested in China. There is no bottom "line" here.

**Comment by xxwncnmb** [comment]
> Is there a bottom line when you say "freedom of speech"Is what you call "freedom of speech" really allowed to say anything? Do you dare to post negative comments about black people on Twitter and FaceBook? Or dare you publicly support negative comments about your black friends?
> No, you dare not. If you dare to say or support these comments, you will surely be punished by the league like clippers owner Donald Sterling, when Adam Silver announced that he was banned for life and fined $2.5 million by the league. What about you? What punishment will you receive???
> We, like you, will not agree with or even make racist remarks, because premier zhou enlai once said, "seek common ground while reserving differences."
> "Racial discrimination" is the bottom line of your "freedom of speech", and "national sovereignty" is the bottom line of our "freedom of speech".
> Your support for "freedom of speech" in Hong Kong is to support their efforts to split the country. In our eyes, this is as serious as "racial discrimination".
> If you don't know our Chinese situation, please comment after you know it or shut up!
> If you do not support the "freedom of speech" of "racial discrimination", please do not support the "freedom of speech" of Hong Kong abandoned waste younth.
> 你们所说的“言论自由”是否是有底线的？难道你们所谓的“言论自由”真的是可以什么都说的吗？你们敢不敢在Twitter、FaceBook上面发表对黑人的负面评论呢？又或者你们是否敢公开支持对于黑人朋友负面的评论呢？
> 不，你们不敢，如果你们敢说或者支持这些评论，你们肯定会像快船老板斯特林（Donald Sterling）一样，他被联盟处罚，肖华（Adam Silver）宣布他被联盟终生禁赛、罚款250万美元，那么你们呢？你们会受到什么处罚？？？
> 我们和你们一样不会赞同甚至发表“种族歧视”相关言论，因为周恩来周总理曾经说过：“求同存异”。
> “种族歧视”是你们“言论自由”的底线，“国家主权”就是我们“言论自由”的底线。
> 你们支持香港“言论自由”，就是支持他们搞“国家分裂”，在我们眼里，这个性质和“种族歧视”一样严重！
> 如果你们不了解我们中国国情请了解之后再来评论要么就闭嘴！
> 如果你们不支持“种族歧视”的“言论自由”那么也请不要支持香港废青们的“言论自由”。

太監就不要討論性生活了！
>你說你們不會贊同發表種族歧視言論？社交媒體說白皮豬，黑鬼的言論還少嗎？不會得到刪除哦。
>哦，國家主權？言論自由？大陸有言論自由？你們是沒有底綫，一次次刷新下限！印度占了那麽多領土怎麽沒見你們發聲？
>支持香港言論自由就是支持他們搞國家分裂？你是沒腦子還是瞎子？這都扯到國家分裂？五大訴求那一條是關於國家分裂了？
>不了解國情請了解之後在來評論，那麽請問你了解美國國情？
>言論自由并不代表你什麽都能說，你們大陸沒有言論自由就不要出來說言論自由！到底誰是雙標狗一目了然！
**腦子是個好東西，但你沒有**

**Comment by 784033619** [comment]
> > Can you represent Hong Kong? Maybe you think that abandoned waste younth can represent Hong Kong?
> 
> @ZioA5260 First, I think calling anyone "abandoned waste" is derogatory.
> Secondly, I think they're representing themselves just fine. It's not my land, it's theirs.
> 
> > if he thinks the country is bad, they can march and demonstrate, they can oppose some actions of the government.
> 
> @784033619 That's interesting.
> 
> > They disrupt public transport in cities, destroy urban construction, destroy shops that do not support them, beat innocent citizens and throw Molotov cocktails at police. I think they look like terrorists.
> 
> Would you support their demonstration if they didn't incur in violent behavior? Going back to the topic of this issue: The information provided by this list is the **least** violent behavior possible and I'm sure it's an example of solidarity. So if you think you can show solidarity with people that want to show their nonconformity with their government, you could support these (foreign) demonstrators.

As long as it's legal, I support it. The problem is that they are illegal now, I don't support them, so will you support them?
只要是合法游行，我就支持；问题是现在他们不合法了，我不支持，那你会去支持吗？

**Comment by 784033619** [comment]
> > Can you represent Hong Kong? Maybe you think that abandoned waste younth can represent Hong Kong?
> 
> @ZioA5260 First, I think calling anyone "abandoned waste" is derogatory.
> Secondly, I think they're representing themselves just fine. It's not my land, it's theirs.
> 
> > if he thinks the country is bad, they can march and demonstrate, they can oppose some actions of the government.
> 
> @784033619 That's interesting.
> 
> > They disrupt public transport in cities, destroy urban construction, destroy shops that do not support them, beat innocent citizens and throw Molotov cocktails at police. I think they look like terrorists.
> 
> Would you support their demonstration if they didn't incur in violent behavior? Going back to the topic of this issue: The information provided by this list is the **least** violent behavior possible and I'm sure it's an example of solidarity. So if you think you can show solidarity with people that want to show their nonconformity with their government, you could support these (foreign) demonstrators.



> > Can you represent Hong Kong? Maybe you think that abandoned waste younth can represent Hong Kong?
> 
> @ZioA5260 First, I think calling anyone "abandoned waste" is derogatory.
> Secondly, I think they're representing themselves just fine. It's not my land, it's theirs.
> 
> > if he thinks the country is bad, they can march and demonstrate, they can oppose some actions of the government.
> 
> @784033619 That's interesting.
> 
> > They disrupt public transport in cities, destroy urban construction, destroy shops that do not support them, beat innocent citizens and throw Molotov cocktails at police. I think they look like terrorists.
> 
> Would you support their demonstration if they didn't incur in violent behavior? Going back to the topic of this issue: The information provided by this list is the **least** violent behavior possible and I'm sure it's an example of solidarity. So if you think you can show solidarity with people that want to show their nonconformity with their government, you could support these (foreign) demonstrators.

As long as it's legal, I support it. The problem is that they are illegal now, I don't support them, so will you support them?
只要是合法游行，我就支持；问题是现在他们不合法了，我不支持，那你会去支持吗？

**Comment by xxwncnmb** [comment]
太監就不要討論性生活了！

你說你們不會贊同發表種族歧視言論？大陸社交媒體上說白皮豬，黑鬼的言論還少嗎？不會得到刪除哦。
[>哦，國家主權？言論自由？大陸有言論自由？你們是沒有底綫，一次次刷新下限！印度占了那麽多領土怎麽沒見你們發聲？] [戰螂們怎麽不出擊呢？](https://www.hk01.com/%E5%8D%B3%E6%99%82%E4%B8%AD%E5%9C%8B/360801/%E5%8D%B0%E6%88%90%E7%AB%8B-%E6%8B%89%E9%81%94%E5%85%8B%E4%B8%AD%E5%A4%AE%E7%9B%B4%E8%BD%84%E5%8D%80-%E6%B6%89%E4%B8%AD%E5%9C%8B%E9%A0%98%E5%9C%9F-%E5%A4%96%E4%BA%A4%E9%83%A8%E6%96%A5%E6%90%8D%E4%B8%AD%E5%9C%8B%E9%A0%98%E5%9C%9F%E4%B8%BB%E6%AC%8A)
支持香港言論自由就是支持他們搞國家分裂？你是沒腦子還是瞎子？這都扯到國家分裂？五大訴求那一條是關於國家分裂了？
不了解國情請了解之後在來評論，那麽請問你了解美國國情？
言論自由并不代表你什麽都能說，你們大陸有言論自由？這是聽過最搞笑的笑話了！
腦子是個好東西，但你沒有

**Comment by RookieZoe** [comment]
> 太監就不要討論性生活了！
> 
> 你說你們不會贊同發表種族歧視言論？大陸社交媒體上說白皮豬，黑鬼的言論還少嗎？不會得到刪除哦。
> [>哦，國家主權？言論自由？大陸有言論自由？你們是沒有底綫，一次次刷新下限！印度占了那麽多領土怎麽沒見你們發聲？] [戰螂們怎麽不出擊呢？](https://www.hk01.com/%E5%8D%B3%E6%99%82%E4%B8%AD%E5%9C%8B/360801/%E5%8D%B0%E6%88%90%E7%AB%8B-%E6%8B%89%E9%81%94%E5%85%8B%E4%B8%AD%E5%A4%AE%E7%9B%B4%E8%BD%84%E5%8D%80-%E6%B6%89%E4%B8%AD%E5%9C%8B%E9%A0%98%E5%9C%9F-%E5%A4%96%E4%BA%A4%E9%83%A8%E6%96%A5%E6%90%8D%E4%B8%AD%E5%9C%8B%E9%A0%98%E5%9C%9F%E4%B8%BB%E6%AC%8A)
> 支持香港言論自由就是支持他們搞國家分裂？你是沒腦子還是瞎子？這都扯到國家分裂？五大訴求那一條是關於國家分裂了？
> 不了解國情請了解之後在來評論，那麽請問你了解美國國情？
> 言論自由并不代表你什麽都能說，你們大陸有言論自由？這是聽過最搞笑的笑話了！
> 腦子是個好東西，但你沒有

What is really happening in HK: [https://youtu.be/jWVkDPUmumI](https://youtu.be/jWVkDPUmumI)

And a wise person who knows what's going on: [https://www.youtube.com/channel/UCaSlyjhR4WC7QhYuaivxb6g/videos](https://www.youtube.com/channel/UCaSlyjhR4WC7QhYuaivxb6g/videos)

送你们一句话：“兼听则明偏听则暗”

**Comment by ZioA5260** [comment]
> [>哦，國家主權？言論自由？大陸有言論自由？你們是沒有底綫，一次次刷新下限！印度占了那麽多領土怎麽沒見你們發聲？] [戰螂們怎麽不出擊呢？](https://www.hk01.com/%E5%8D%B3%E6%99%82%E4%B8%AD%E5%9C%8B/360801/%E5%8D%B0%E6%88%90%E7%AB%8B-%E6%8B%89%E9%81%94%E5%85%8B%E4%B8%AD%E5%A4%AE%E7%9B%B4%E8%BD%84%E5%8D%80-%E6%B6%89%E4%B8%AD%E5%9C%8B%E9%A0%98%E5%9C%9F-%E5%A4%96%E4%BA%A4%E9%83%A8%E6%96%A5%E6%90%8D%E4%B8%AD%E5%9C%8B%E9%A0%98%E5%9C%9F%E4%B8%BB%E6%AC%8A)
即使62年的中国内外交困，中国依旧赢得了中印战争。如今的印度继续跳下去，自然会有中国人民解放军，轮不到你在这操心
> 支持香港言論自由就是支持他們搞國家分裂？你是沒腦子還是瞎子？這都扯到國家分裂？五大訴求那一條是關於國家分裂了？
现在讨论的到底是在香港言论自由还是在香港分裂，你的脑子不会是没搞清楚吧？香港废青们现在的诉求不是分裂国家而是言论自由？
> 不了解國情請了解之後在來評論，那麽請問你了解美國國情？
所以并没有中国莫雷跳出来评论美国什么
> 言論自由并不代表你什麽都能說，你們大陸有言論自由？這是聽過最搞笑的笑話了！
我们也从来没强调过言论自由，但是我们强调主权完整
> 腦子是個好東西，但你沒有
我的妈妈曾经教导我要做个好人，但是现在看来不是所有人都有妈妈

**Comment by RookieZoe** [comment]
> Discriminative speech in US may cost you a job or two, but any political speech that's not rubber-stamped by the authority may get you arrested in China. There is no bottom "line" here.

F*cking bullshit fully filled in you stupid mouth.

Do you even lived in China? Or all you knows about China were told by western medias.

**Comment by janicege** [comment]
> > Your comment doesn't make a disservice to the fact that governments should tend to their people needs, as you're part of a democracy.
> > Now, part of your country feels like their government is not representing or taking care of their needs. You have a choice: you either listen and understand those needs, and take action so your government service them, or you simply accept the fact that your government is not needed anymore, and move on.
> > Borders, sovereignty, are imaginary lines, put there for ease of management, and if you can't manage them, and you keep fighting for it, you are not "protecting your sovereignty", that is just **greed**.
> > I know that you care about your country.
> > Countries are made by the people, for the people, and people in the Hong Kong area don't feel like part of your country any more. That's how I feel about this whole thing.
> 
> But they are still Chinese after all, they have not changed their nationality, if he thinks the country is bad, they can march and demonstrate, they can oppose some actions of the government. But do you know what they did? They disrupt public transport in cities, destroy urban construction, destroy shops that do not support them, beat innocent citizens and throw Molotov cocktails at police. I think they look like terrorists.
> 但他们毕竟还是中国人，还没有改国籍，如果他觉得国家不好，他们可以游行示威，可以反对政府一些做法。但是你知道他们做了些什么吗？他们破坏城市公共交通，毁坏城市建设，不支持他们的商店就破坏，殴打无辜市民，向警察扔燃烧瓶。我觉得他们这像恐怖分子。

I don't support vandalism but you know what? The Hong Kong people have been demonstrating for years requesting more civic rights, and the government listens to the people at all? HK is run by a broke system where many of the senior officials have privileges to send their kids overseas, enjoy dual citizenship with foreign passports while kowtowing to their CCP masters. So what's the check and balance of the government? Who can restrain them if they do something against the people?

**Comment by caffeine-overload** [comment]
yikes

**Comment by recolic** [comment]
btw, 此issue的开辟者完全没有对言论自由这个词语的含义的认知，看起来像一个与现代社会隔绝的中世纪子民的观点。
公司作为一个独立的个体，有权利按照自己的需求制定TOS,并按照契约的规定来管理自己平台中的内容，只要不违反宪法对言论自由的要求的底线即可。
政府作为公权力的象征，在没有契约的情况下，无权对言论进行审查，更没有权利因为言论来直接定罪。这是言论自由的一个体现。
您举出了公司按契约对内容的管理的例子，来为公权力迫害异见者的纳粹主义行径辩护。这岂不是可笑。

(举一个具体的例子，香港问题上，政府对媒体和国内互联网的严格控制，使得臣民按照政府的意愿对事实产生定向的误解，从而激发民族主义情绪的做法，正是没有言论自由的恶果的体现。)

**Comment by weathon** [comment]
> 但他们毕竟还是中国人，还没有改国籍，如果他觉得国家不好，他们可以游行示威，可以反对政府一些做法。但是你知道他们做了些什么吗？他们破坏城市公共交通，毁坏城市建设，不支持他们的商店就破坏，殴打无辜市民，向警察扔燃烧瓶。我觉得他们这像恐怖分子。

就知道github五毛也不少，你去看看是谁无差别攻击平民？警察还是示威者？
