### ISSUE TITLE
White Americans should compensate blacks for one million dollars each because their ancestors used to slaughter blacks and sell black slaves.

### ISSUE THREAD

**Issue by ThunderLT** [caffeine-overload/bandinchina#43]

**Comment by caffeine-overload** [comment]
If you went and said this in America, you would get a standing ovation in some neighbourhoods

What's the point of this comment?

**Comment by cirosantilli** [comment]
See also: https://github.com/cirosantilli/china-dictatorship/tree/4f91b66bc26a3b7216cf7f037033ff42b8623377#western-democracies-are-not-perfect
