### ISSUE TITLE
The 9/11 incident is the retribution that Americans deserve. They slaughtered Arabs and Islamists and caused revenge from extremists. This is my freedom of speech. The CIA and the US aircraft carrier can kill me even in Shanghai, just like the Snowden incident. The Americans are calling for privacy protection while eavesdropping on the world’s bed

### ISSUE THREAD

**Issue by ThunderLT** [caffeine-overload/bandinchina#48]

**Comment by caffeine-overload** [comment]
You aren't the first person to argue that the US's foreign policy provoked 9/11, plenty of Americans have made the same argument, and no, the US won't shoot you for saying that.

**Comment by cirosantilli** [comment]
See also: https://github.com/cirosantilli/china-dictatorship/tree/4f91b66bc26a3b7216cf7f037033ff42b8623377#western-democracies-are-not-perfect
