### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by IzzyData** [caffeine-overload/bandinchina#5]
A date occurred column could be useful.

**Comment by ryaniskira** [comment]
That might be helpful but one can usually look at the sources provided for dates.

**Comment by Faunsce** [comment]
I second this

**Comment by dmathisen** [comment]
Looks like it was added (close issue?)
Is there any need for the "Date Added" column?

**Comment by caffeine-overload** [comment]
Yeah, someone made a pull request. 

As for needing the "date added" column, maybe we should open a new issue and gather some opinions on what to do?

**Comment by Faunsce** [comment]
PR #16 This feature has been added. Recommend closing the issue
