### ISSUE TITLE
Coward.

### ISSUE THREAD

**Issue by RookieZoe** [caffeine-overload/bandinchina#51]
你们一边大谈特谈“明主自由”一边捂着耳朵叫着“我不听我不听”的样子真可笑，一群懦夫！

**Comment by luiseok** [comment]
![253fa0ee6c91066d81b762e7f8f8f010](https://user-images.githubusercontent.com/3125044/66639819-930bac80-ec52-11e9-9489-16c02e0ce9e1.jpg)

**Comment by theJian** [comment]
No one stops you from maintaining your own repo.

**Comment by RookieZoe** [comment]
> No one stops you from maintaining your own repo.

OK, No more arguments. And no one stops you from being blind, either. So I'll close this issue. Goodbye.
