### ISSUE TITLE
haha

### ISSUE THREAD

**Issue by newlinhan** [caffeine-overload/bandinchina#54]
boy you are playing fire

**Comment by Faunsce** [comment]
We should close this issue. its polluting our list

**Comment by MoistCode** [comment]
I believe this issue should also be closed.

Issues should be for bug reporting, feature requests, and/or task trackers. Not for political discussions that do not fall under any of the previously mentioned three categories.

This goes for both those FOR and those OPPOSED. It does not matter. I believe those discussions belong somewhere else.

Hell, we can make a public chat box or forum on the site if y'all want to talk about it there.

**Comment by weathon** [comment]
Who is playing with fire？I think this is very easy to get the answer -

**Comment by weathon** [comment]
@newlinhan CCP
