### ISSUE TITLE
Append the list with contents of the Business Hall of Bootlickers

### ISSUE THREAD

**Issue by LenKagetsu** [caffeine-overload/bandinchina#69]
Likely the post that inspired this hub, here it is on r/hongkong: https://old.reddit.com/r/HongKong/comments/dge9ib/i_posted_lists_of_china_bootlickers_atrocities_in/

A few notable ones are missing, namely EA and Cisco.

**Comment by caffeine-overload** [comment]
Actually not, I posted a link to my repo earlier than that post appeared but it didn't get much traction, I think this one and that one were made pretty much at the same time. I copied most into here when I saw that post, I'll recheck

**Comment by LenKagetsu** [comment]
So you did, was too lazy to check timestamps as is usual for me.
