### ISSUE TITLE
Add Google's Dragonfly project

### ISSUE THREAD

**Issue by kevinsmia1939** [caffeine-overload/bandinchina#71]
Google create Dragonfly project which is a Google Search but for Chinese market. Dragonfly project would require users to log in to perform searches, track their location — and share the resulting history with a Chinese partner who would have “unilateral access” to the data.

Without internal leak and public pressure, Google would have continue its development which show that they care more for profit than human right.

https://theintercept.com/2018/09/21/google-suppresses-memo-revealing-plans-to-closely-track-search-users-in-china/

https://www.cnet.com/news/report-google-suppressed-an-explosive-memo-about-its-chinese-search-engine/

https://theintercept.com/2018/12/17/google-china-censored-search-engine-2/

https://www.independent.co.uk/life-style/gadgets-and-tech/news/google-china-ban-project-dragonfly-search-engine-project-a9007956.html

**Comment by caffeine-overload** [comment]
I don't think this is in scope of the current blacklist, but there are talks to have several more lists for subjects like these
