### ISSUE TITLE
technic should not associate with politics!!!!!!!!!!!!

### ISSUE THREAD

**Issue by Castleeee** [caffeine-overload/bandinchina#89]

**Comment by hmilyyang** [comment]
Agree！

**Comment by LenKagetsu** [comment]
Pop quiz; what happened in Tiananmen Square on the 4th of June in 1989?

**Comment by xuexiaoao** [comment]
Agree!

**Comment by strgalt-t** [comment]
technology is political

**Comment by jackychang94** [comment]
When did China keep politics out of anything?

**Comment by franklingu** [comment]
> Pop quiz; what happened in Tiananmen Square on the 4th of June in 1989?

what do you think happened there in 1989?

**Comment by caffeine-overload** [comment]
I'm entitled to use github for anything that doesn't violate their TOS

**Comment by cirosantilli** [comment]
See also: https://github.com/cirosantilli/china-dictatorship/tree/75356679ab6509aa6608804f57e9414bc347ff48#you-are-using-stack-overflow-in-a-way-that-it-was-not-meant-to-be-used-so-what-you-are-doing-is-in-principle-wrong
