### ISSUE TITLE
LG Group, a South Korean company, should also be added.

### ISSUE THREAD

**Issue by freedomHKong** [caffeine-overload/bandinchina#95]
They are doing business using Huawei's wireless equipment.
They also have a technical agreement with the Chinese government to build an OLED factory in China.
OLED panels that are made like that are going abroad.
LG Group is trying to make money by looking good to the Chinese Communist Party.
Using Huawei's equipment at this point is ultimately helping the Communist Party of China.
Therefore, LG Group should also be included in the list.

**Comment by LenKagetsu** [comment]
Using a company's product does not constitute kowtowing to their demands, which is what the list is about. China having its fingers in such a massive amount of industries is a major problem but it's something that is extremely difficult to fully avoid.

**Comment by caffeine-overload** [comment]
Yeah, I think things like this needs to go on a separate list, unless

 >  LG Group is trying to make money by looking good to the Chinese Communist Party.

It depends on what they did to impress the CCP.

But a lot of people have expressed the wish to try to boycott anything made in China, or anything made by shady Chinese companies like Huawei, so such a list will also be useful
